data:
  raw_dir: data/raw
  processed_dir: data/processed
  processed_file: processed_data.h5
  splits_dir: data/raw_splits
  manifest_file: data/manifest_new_with_filtered_test_density_with_clipping_500k_maxlen.csv
  feature_transform: true
  feature_centering: true
  batch_size: 2 #8 max batch for sum aggregators #6 max batch for concat_stats aggregator #4 max batch for attn_pool aggregator
  num_workers: 8
  samples_per_complex: 5
  use_interchain_ca_distances: true
  use_interchain_pae: false
  
model:
  input_dim: 4
  aggregator: concat_stats_by_set_size
  phi_hidden_dims: [128, 32, 64]
  rho_hidden_dims: [256, 256, 256]

training:
  adaptive_weight: true
  epochs: 150
  lr: !!float 1e-3
  weight_decay: !!float 1e-5
  smooth_l1_beta: 0.5
  weighted_loss: true
  bucket_balance: false
  num_buckets: 4
  seed: 42
  lr_scheduler_type: "WarmupHoldLinear"  # or "ReduceLROnPlateau" or "WarmupHoldLinear"
  add_ranking_loss: true      # Whether to add the ranking loss
  ranking_loss_type: "one_minus_rho"  # "fisher" or "one_minus_rho"
