# Default configuration for project

num_samples_per_complex: 10 # Number of samples per complex used in each epoch

data:
  raw_dir: data/raw
  processed_dir: data/processed
  processed_file: processed_data.h5
  splits_dir: data/raw_splits
  manifest_file: data/manifest.csv

model:
  input_dim: 3
  aggregator: sum
  phi_hidden_dims: [128, 128, 128]
  rho_hidden_dims: [128, 128, 128]

training:
  batch_size: 8
  num_workers: 4
  epochs: 100
  lr: 0.0001
  bucket_balance: true
  num_buckets: 4
  seed: 42
