
num_samples_per_complex: None # Number of samples per complex used in each epoch

data:
  raw_dir: data/raw
  processed_dir: data/processed
  processed_file: processed_data.h5
  splits_dir: data/raw_splits
  manifest_file: data/manifest_filtered_pae_centered_density_with_clipping.csv
  feature_transform: true
  feature_centering: true

model:
  input_dim: 3
  aggregator: concat_stats_by_set_size
  phi_hidden_dims: [128, 128, 128]
  rho_hidden_dims: [128, 128, 128]

training:
  batch_size: 4 #8 max batch for sum aggregators #6 max batch for concat_stats aggregator #4 max batch for attn_pool aggregator
  num_workers: 4
  epochs: 100
  lr: !!float 1e-3
  weight_decay: !!float 1e-5
  smooth_l1_beta: 0.5
  weighted_loss: true
  bucket_balance: false
  num_buckets: 4
  seed: 42
  lr_scheduler_factor: 0.75
  lr_scheduler_patience: 15
  min_lr: !!float 2e-5
  adaptive_weight: true
