# Default configuration for project

num_samples_per_complex: 20 # Number of samples per complex used in each epoch

data:
  raw_dir: data/raw
  processed_dir: data/processed
  processed_file: processed_data.h5
  splits_dir: data/raw_splits
  manifest_file: data/manifest_with_ptm_no_normalization.csv
  feature_transform: true

model:
  input_dim: 3
  aggregator: sum_by_set_size
  phi_hidden_dims: [128, 128, 128]
  rho_hidden_dims: [128, 128, 128]

training:
  batch_size: 8 #8 max batch for sum aggregators #6 max batch for concat_stats aggregator #4 max batch for attn_pool aggregator
  num_workers: 4
  epochs: 10
  lr: 0.001
  weight_decay: 0.00001
  smooth_l1_beta: 1
  weighted_loss: false
  bucket_balance: true
  num_buckets: 4
  seed: 42
  lr_scheduler_factor: 0.66
  lr_scheduler_patience: 10
